"""new fields in user model

Revision ID: 56425b6019d1
Revises: 3e546557ae1d
Create Date: 2023-03-02 18:15:31.934500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56425b6019d1'
down_revision = '3e546557ae1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
